theme: minima
title: "Изучение основ менеджмента"
description: "Системное мышление, операционный менеджмент и управление проектами"
author: "Евгений Терехов"
domain: eugene-terekhov-s-learning.github.io
url: https://eugene-terekhov-s-learning.github.io
baseurl: /learn-management
github_username: nergal-perm
linkedin_username: eterehov-java-lead
youtube_username: "@EugeneWritesCode"
rss: rss
minima:
  date_format: "%Y-%m-%d"
disqus:
  shortname: learn-management-1
plugins:
  - jekyll-gist
exclude: [ "jira.md" ]
collections:
  decisions:
    output: true
    permalink: /decisions/:name
